<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class WargaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('warga')->insert([
            // RT 001
            [
                'nik' => '1234567890123456',
                'nama' => 'Budi Santoso',
                'id_rt' => 1,
                'rw' => '001',
                'jenis_kelamin' => 'Laki-laki',
                'golongan_darah' => 'A',
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '1980-01-01',
                'alamat_ktp' => 'Jl. Merdeka No. 1',
                'alamat_domisili' => 'Jl. Merdeka No. 1',
                'no_hp' => '081234567890',
                'agama' => 'Islam',
                'pekerjaan' => 'Pegawai Negeri',
                'status_kawin' => 'Kawin',
                'gambar_ktp' => 'budi_ktp.jpg',
                'status_warga' => 'Aktif',
                'catatan_status' => 'Tidak ada',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => '2345678901234567',
                'nama' => 'Siti Aminah',
                'id_rt' => 1,
                'rw' => '001',
                'jenis_kelamin' => 'Perempuan',
                'golongan_darah' => 'B',
                'tempat_lahir' => 'Bandung',
                'tanggal_lahir' => '1990-02-02',
                'alamat_ktp' => 'Jl. Sudirman No. 2',
                'alamat_domisili' => 'Jl. Sudirman No. 2',
                'no_hp' => '082345678901',
                'agama' => 'Kristen',
                'pekerjaan' => 'Guru',
                'status_kawin' => 'Belum Kawin',
                'gambar_ktp' => 'siti_ktp.jpg',
                'status_warga' => 'Aktif',
                'catatan_status' => 'Tidak ada',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // RT 002
            [
                'nik' => '3456789012345678',
                'nama' => 'Andi Wijaya',
                'id_rt' => 2,
                'rw' => '001',
                'jenis_kelamin' => 'Laki-laki',
                'golongan_darah' => 'O',
                'tempat_lahir' => 'Surabaya',
                'tanggal_lahir' => '2000-03-03',
                'alamat_ktp' => 'Jl. Diponegoro No. 3',
                'alamat_domisili' => 'Jl. Diponegoro No. 3',
                'no_hp' => '083456789012',
                'agama' => 'Hindu',
                'pekerjaan' => 'Mahasiswa',
                'status_kawin' => 'Belum Kawin',
                'gambar_ktp' => 'andi_ktp.jpg',
                'status_warga' => 'Aktif',
                'catatan_status' => 'Tidak ada',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => '4567890123456789',
                'nama' => 'Rina Sari',
                'id_rt' => 2,
                'rw' => '001',
                'jenis_kelamin' => 'Perempuan',
                'golongan_darah' => 'AB',
                'tempat_lahir' => 'Malang',
                'tanggal_lahir' => '1995-04-04',
                'alamat_ktp' => 'Jl. Pahlawan No. 4',
                'alamat_domisili' => 'Jl. Pahlawan No. 4',
                'no_hp' => '084567890123',
                'agama' => 'Buddha',
                'pekerjaan' => 'Dokter',
                'status_kawin' => 'Kawin',
                'gambar_ktp' => 'rina_ktp.jpg',
                'status_warga' => 'Aktif',
                'catatan_status' => 'Tidak ada',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // RT 003
            [
                'nik' => '5678901234567890',
                'nama' => 'Dedi Pratama',
                'id_rt' => 3,
                'rw' => '001',
                'jenis_kelamin' => 'Laki-laki',
                'golongan_darah' => 'B',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '1985-05-05',
                'alamat_ktp' => 'Jl. Malioboro No. 5',
                'alamat_domisili' => 'Jl. Malioboro No. 5',
                'no_hp' => '085678901234',
                'agama' => 'Islam',
                'pekerjaan' => 'Pengusaha',
                'status_kawin' => 'Kawin',
                'gambar_ktp' => 'dedi_ktp.jpg',
                'status_warga' => 'Aktif',
                'catatan_status' => 'Tidak ada',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => '6789012345678901',
                'nama' => 'Lina Marlina',
                'id_rt' => 3,
                'rw' => '001',
                'jenis_kelamin' => 'Perempuan',
                'golongan_darah' => 'A',
                'tempat_lahir' => 'Semarang',
                'tanggal_lahir' => '1992-06-06',
                'alamat_ktp' => 'Jl. Pandanaran No. 6',
                'alamat_domisili' => 'Jl. Pandanaran No. 6',
                'no_hp' => '086789012345',
                'agama' => 'Katolik',
                'pekerjaan' => 'Perawat',
                'status_kawin' => 'Belum Kawin',
                'gambar_ktp' => 'lina_ktp.jpg',
                'status_warga' => 'Aktif',
                'catatan_status' => 'Tidak ada',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // RT 004
            [
                'nik' => '7890123456789012',
                'nama' => 'Tono Wijaya',
                'id_rt' => 4,
                'rw' => '001',
                'jenis_kelamin' => 'Laki-laki',
                'golongan_darah' => 'O',
                'tempat_lahir' => 'Medan',
                'tanggal_lahir' => '1988-07-07',
                'alamat_ktp' => 'Jl. Sisingamangaraja No. 7',
                'alamat_domisili' => 'Jl. Sisingamangaraja No. 7',
                'no_hp' => '087890123456',
                'agama' => 'Konghucu',
                'pekerjaan' => 'Petani',
                'status_kawin' => 'Kawin',
                'gambar_ktp' => 'tono_ktp.jpg',
                'status_warga' => 'Aktif',
                'catatan_status' => 'Tidak ada',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => '8901234567890123',
                'nama' => 'Sari Dewi',
                'id_rt' => 4,
                'rw' => '001',
                'jenis_kelamin' => 'Perempuan',
                'golongan_darah' => 'AB',
                'tempat_lahir' => 'Palembang',
                'tanggal_lahir' => '1993-08-08',
                'alamat_ktp' => 'Jl. Rajawali No. 8',
                'alamat_domisili' => 'Jl. Rajawali No. 8',
                'no_hp' => '088901234567',
                'agama' => 'Islam',
                'pekerjaan' => 'Karyawan Swasta',
                'status_kawin' => 'Belum Kawin',
                'gambar_ktp' => 'sari_ktp.jpg',
                'status_warga' => 'Aktif',
                'catatan_status' => 'Tidak ada',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
