<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class WargaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('warga')->insert([
            // Ketua RW
            [
                'nik' => '3507231505800001',
                'nama' => 'Budi Santoso',
                'id_rt' => 1,
                'id_keluarga' => 1,
                'rw' => '001',
                'jenis_kelamin' => 'Laki-laki',
                'golongan_darah' => 'A',
                'tempat_lahir' => 'Malang',
                'tanggal_lahir' => '1980-05-15',
                'alamat_ktp' => 'Jl. Merdeka No. 1, Karangploso, Tegalgondo, Malang',
                'alamat_domisili' => 'Jl. Merdeka No. 1, Karangploso, Tegalgondo, Malang',
                'no_hp' => '081234567890',
                'agama' => 'Islam',
                'pekerjaan' => 'Ketua RW',
                'status_kawin' => 'Kawin',
                'gambar_ktp' => 'budi_ktp.jpg',
                'status_warga' => 'Aktif',
                'catatan_status' => 'Warga telah terdaftar dalam sistem',
                'status_keluarga' => 'Kepala Keluarga',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Sekretaris RW
            [
                'nik' => '3507230202900002',
                'nama' => 'Siti Aminah',
                'id_rt' => 1,
                'id_keluarga' => 1,
                'rw' => '001',
                'jenis_kelamin' => 'Perempuan',
                'golongan_darah' => 'B',
                'tempat_lahir' => 'Malang',
                'tanggal_lahir' => '1990-02-02',
                'alamat_ktp' => 'Jl. Sudirman No. 2, Karangploso, Tegalgondo, Malang',
                'alamat_domisili' => 'Jl. Merdeka No. 1, Karangploso, Tegalgondo, Malang',
                'no_hp' => '082345678901',
                'agama' => 'Islam',
                'pekerjaan' => 'Sekretaris RW',
                'status_kawin' => 'Kawin',
                'gambar_ktp' => 'siti_ktp.jpg',
                'status_warga' => 'Aktif',
                'catatan_status' => 'Warga telah terdaftar dalam sistem',
                'status_keluarga' => 'Istri',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Bendahara RW
            [
                'nik' => '3507230303000003',
                'nama' => 'Andi Wijaya',
                'id_rt' => 3,
                'id_keluarga' => null,
                'rw' => '001',
                'jenis_kelamin' => 'Laki-laki',
                'golongan_darah' => 'O',
                'tempat_lahir' => 'Malang',
                'tanggal_lahir' => '2000-03-03',
                'alamat_ktp' => 'Jl. Diponegoro No. 3, Karangploso, Tegalgondo, Malang',
                'alamat_domisili' => 'Jl. Diponegoro No. 3, Karangploso, Tegalgondo, Malang',
                'no_hp' => '083456789012',
                'agama' => 'Islam',
                'pekerjaan' => 'Bendahara RW',
                'status_kawin' => 'Belum Kawin',
                'gambar_ktp' => 'andi_ktp.jpg',
                'status_warga' => 'Aktif',
                'catatan_status' => 'Warga telah terdaftar dalam sistem',
                'status_keluarga' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Ketua RT 1
            [
                'nik' => '3507231505850001',
                'nama' => 'Dedi Pratama',
                'id_rt' => 1,
                'id_keluarga' => 2,
                'rw' => '001',
                'jenis_kelamin' => 'Laki-laki',
                'golongan_darah' => 'B',
                'tempat_lahir' => 'Malang',
                'tanggal_lahir' => '1985-05-15',
                'alamat_ktp' => 'Jl. Malioboro No. 5, Karangploso, Tegalgondo, Malang',
                'alamat_domisili' => 'Jl. Malioboro No. 5, Karangploso, Tegalgondo, Malang',
                'no_hp' => '085678901234',
                'agama' => 'Islam',
                'pekerjaan' => 'Ketua RT',
                'status_kawin' => 'Kawin',
                'gambar_ktp' => 'dedi_ktp.jpg',
                'status_warga' => 'Aktif',
                'catatan_status' => 'Warga telah terdaftar dalam sistem',
                'status_keluarga' => 'Kepala Keluarga',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Sekretaris RT 1
            [
                'nik' => '3507230606920002',
                'nama' => 'Lina Marlina',
                'id_rt' => 1,
                'id_keluarga' => 2,
                'rw' => '001',
                'jenis_kelamin' => 'Perempuan',
                'golongan_darah' => 'A',
                'tempat_lahir' => 'Malang',
                'tanggal_lahir' => '1992-06-06',
                'alamat_ktp' => 'Jl. Pandanaran No. 6, Karangploso, Tegalgondo, Malang',
                'alamat_domisili' => 'Jl. Malioboro No. 5, Karangploso, Tegalgondo, Malang',
                'no_hp' => '086789012345',
                'agama' => 'Islam',
                'pekerjaan' => 'Sekretaris RT',
                'status_kawin' => 'Kawin',
                'gambar_ktp' => 'lina_ktp.jpg',
                'status_warga' => 'Aktif',
                'catatan_status' => 'Warga telah terdaftar dalam sistem',
                'status_keluarga' => 'Istri',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Ketua RT 2
            [
                'nik' => '3507230707880003',
                'nama' => 'Tono Wijaya',
                'id_rt' => 2,
                'id_keluarga' => null,
                'rw' => '001',
                'jenis_kelamin' => 'Laki-laki',
                'golongan_darah' => 'O',
                'tempat_lahir' => 'Malang',
                'tanggal_lahir' => '1988-07-07',
                'alamat_ktp' => 'Jl. Sisingamangaraja No. 7, Karangploso, Tegalgondo, Malang',
                'alamat_domisili' => 'Jl. Sisingamangaraja No. 7, Karangploso, Tegalgondo, Malang',
                'no_hp' => '087890123456',
                'agama' => 'Islam',
                'pekerjaan' => 'Ketua RT',
                'status_kawin' => 'Belum Kawin',
                'gambar_ktp' => 'tono_ktp.jpg',
                'status_warga' => 'Aktif',
                'catatan_status' => 'Warga telah terdaftar dalam sistem',
                'status_keluarga' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Ketua RT 3
            [
                'nik' => '3507230808930004',
                'nama' => 'Sari Dewi',
                'id_rt' => 3,
                'id_keluarga' => null,
                'rw' => '001',
                'jenis_kelamin' => 'Perempuan',
                'golongan_darah' => 'AB',
                'tempat_lahir' => 'Malang',
                'tanggal_lahir' => '1993-08-08',
                'alamat_ktp' => 'Jl. Rajawali No. 8, Karangploso, Tegalgondo, Malang',
                'alamat_domisili' => 'Jl. Rajawali No. 8, Karangploso, Tegalgondo, Malang',
                'no_hp' => '088901234567',
                'agama' => 'Islam',
                'pekerjaan' => 'Ketua RT',
                'status_kawin' => 'Belum Kawin',
                'gambar_ktp' => 'sari_ktp.jpg',
                'status_warga' => 'Aktif',
                'catatan_status' => 'Warga telah terdaftar dalam sistem',
                'status_keluarga' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Ketua RT 4
            [
                'nik' => '3507230404950004',
                'nama' => 'Rina Sari',
                'id_rt' => 4,
                'id_keluarga' => null,
                'rw' => '001',
                'jenis_kelamin' => 'Perempuan',
                'golongan_darah' => 'AB',
                'tempat_lahir' => 'Malang',
                'tanggal_lahir' => '1995-04-04',
                'alamat_ktp' => 'Jl. Pahlawan No. 4, Karangploso, Tegalgondo, Malang',
                'alamat_domisili' => 'Jl. Pahlawan No. 4, Karangploso, Tegalgondo, Malang',
                'no_hp' => '084567890123',
                'agama' => 'Islam',
                'pekerjaan' => 'Ketua RT',
                'status_kawin' => 'Belum Kawin',
                'gambar_ktp' => 'rina_ktp.jpg',
                'status_warga' => 'Aktif',
                'catatan_status' => 'Warga telah terdaftar dalam sistem',
                'status_keluarga' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Warga RT 1
            [
                'nik' => '3507231505040001',
                'nama' => 'Rudi Hartono',
                'id_rt' => 1,
                'id_keluarga' => null,
                'rw' => '001',
                'jenis_kelamin' => 'Laki-laki',
                'golongan_darah' => 'A',
                'tempat_lahir' => 'Malang',
                'tanggal_lahir' => '2004-05-15',
                'alamat_ktp' => 'Jl. Kebon Sirih No. 9, Karangploso, Tegalgondo, Malang',
                'alamat_domisili' => 'Jl. Kebon Sirih No. 9, Karangploso, Tegalgondo, Malang',
                'no_hp' => '089012345678',
                'agama' => 'Islam',
                'pekerjaan' => 'Mahasiswa',
                'status_kawin' => 'Belum Kawin',
                'gambar_ktp' => 'rudi_ktp.jpg',
                'status_warga' => 'Aktif',
                'catatan_status' => 'Warga telah terdaftar dalam sistem',
                'status_keluarga' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => '3507231505040002',
                'nama' => 'Rudi Setyo Wibowo',
                'id_rt' => 1,
                'id_keluarga' => null,
                'rw' => '001',
                'jenis_kelamin' => 'Laki-laki',
                'golongan_darah' => 'A',
                'tempat_lahir' => 'Malang',
                'tanggal_lahir' => '2004-05-15',
                'alamat_ktp' => 'Jl. Kebon Sirih No. 10, Karangploso, Tegalgondo, Malang',
                'alamat_domisili' => 'Jl. Kebon Sirih No. 10, Karangploso, Tegalgondo, Malang',
                'no_hp' => '089012345678',
                'agama' => 'Islam',
                'pekerjaan' => 'Mahasiswa',
                'status_kawin' => 'Belum Kawin',
                'gambar_ktp' => 'rudi2_ktp.jpg',
                'status_warga' => 'Aktif',
                'catatan_status' => 'Warga telah terdaftar dalam sistem',
                'status_keluarga' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => '3507231010950003',
                'nama' => 'Siti Ayu Putri',
                'id_rt' => 1,
                'id_keluarga' => null,
                'rw' => '001',
                'jenis_kelamin' => 'Perempuan',
                'golongan_darah' => 'B',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '1995-10-10',
                'alamat_ktp' => 'Jl. Magelang No. 11',
                'alamat_domisili' => 'Jl. Magelang No. 11',
                'no_hp' => '081234567890',
                'agama' => 'Hindu',
                'pekerjaan' => 'Guru',
                'status_kawin' => 'Belum Kawin',
                'gambar_ktp' => 'siti_ktp.jpg',
                'status_warga' => 'Aktif',
                'catatan_status' => 'Warga telah terdaftar dalam sistem',
                'status_keluarga' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => '3507231111850004',
                'nama' => 'Budi Agung Wijaya',
                'id_rt' => 1,
                'id_keluarga' => null,
                'rw' => '001',
                'jenis_kelamin' => 'Laki-laki',
                'golongan_darah' => 'O',
                'tempat_lahir' => 'Surabaya',
                'tanggal_lahir' => '1985-11-11',
                'alamat_ktp' => 'Jl. Gubeng No. 12',
                'alamat_domisili' => 'Jl. Gubeng No. 12',
                'no_hp' => '082345678901',
                'agama' => 'Buddha',
                'pekerjaan' => 'Dokter',
                'status_kawin' => 'Kawin',
                'gambar_ktp' => 'budi_ktp.jpg',
                'status_warga' => 'Aktif',
                'catatan_status' => 'Warga telah terdaftar dalam sistem',
                'status_keluarga' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => '3507231212900005',
                'nama' => 'Ratna Wati Sari',
                'id_rt' => 1,
                'id_keluarga' => null,
                'rw' => '001',
                'jenis_kelamin' => 'Perempuan',
                'golongan_darah' => 'AB',
                'tempat_lahir' => 'Bandung',
                'tanggal_lahir' => '1990-12-12',
                'alamat_ktp' => 'Jl. Dago No. 13',
                'alamat_domisili' => 'Jl. Dago No. 13',
                'no_hp' => '083456789012',
                'agama' => 'Kristen',
                'pekerjaan' => 'Pengusaha',
                'status_kawin' => 'Belum Kawin',
                'gambar_ktp' => 'ratna_ktp.jpg',
                'status_warga' => 'Aktif',
                'catatan_status' => 'Warga telah terdaftar dalam sistem',
                'status_keluarga' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Warga RT 2
            [
                'nik' => '3507231010950001',
                'nama' => 'Susi Wati',
                'id_rt' => 2,
                'id_keluarga' => null,
                'rw' => '001',
                'jenis_kelamin' => 'Perempuan',
                'golongan_darah' => 'B',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '1995-10-10',
                'alamat_ktp' => 'Jl. Magelang No. 10',
                'alamat_domisili' => 'Jl. Magelang No. 10',
                'no_hp' => '081234567890',
                'agama' => 'Hindu',
                'pekerjaan' => 'Guru',
                'status_kawin' => 'Belum Kawin',
                'gambar_ktp' => 'susi_ktp.jpg',
                'status_warga' => 'Aktif',
                'catatan_status' => 'Warga telah terdaftar dalam sistem',
                'status_keluarga' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => '3507230205920002',
                'nama' => 'Amira Lestari',
                'id_rt' => 2,
                'id_keluarga' => null,
                'rw' => '001',
                'jenis_kelamin' => 'Perempuan',
                'golongan_darah' => 'A',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '1992-05-05',
                'alamat_ktp' => 'Jl. Magelang No. 11',
                'alamat_domisili' => 'Jl. Magelang No. 11',
                'no_hp' => '081234567891',
                'agama' => 'Islam',
                'pekerjaan' => 'Pengusaha',
                'status_kawin' => 'Belum Kawin',
                'gambar_ktp' => 'siti_ktp.jpg',
                'status_warga' => 'Aktif',
                'catatan_status' => 'Warga telah terdaftar dalam sistem',
                'status_keluarga' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => '3507230808900003',
                'nama' => 'Rahmat Hidayat',
                'id_rt' => 2,
                'id_keluarga' => null,
                'rw' => '001',
                'jenis_kelamin' => 'Laki-laki',
                'golongan_darah' => 'B',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '1990-08-08',
                'alamat_ktp' => 'Jl. Magelang No. 12',
                'alamat_domisili' => 'Jl. Magelang No. 12',
                'no_hp' => '082345678902',
                'agama' => 'Kristen',
                'pekerjaan' => 'Guru',
                'status_kawin' => 'Kawin',
                'gambar_ktp' => 'rahmat_ktp.jpg',
                'status_warga' => 'Aktif',
                'catatan_status' => 'Warga telah terdaftar dalam sistem',
                'status_keluarga' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => '3507230303950004',
                'nama' => 'Sri Wulan',
                'id_rt' => 2,
                'id_keluarga' => null,
                'rw' => '001',
                'jenis_kelamin' => 'Perempuan',
                'golongan_darah' => 'AB',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '1995-03-03',
                'alamat_ktp' => 'Jl. Magelang No. 13',
                'alamat_domisili' => 'Jl. Magelang No. 13',
                'no_hp' => '083456789013',
                'agama' => 'Hindu',
                'pekerjaan' => 'Dokter',
                'status_kawin' => 'Belum Kawin',
                'gambar_ktp' => 'sri_ktp.jpg',
                'status_warga' => 'Aktif',
                'catatan_status' => 'Warga telah terdaftar dalam sistem',
                'status_keluarga' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => '3507230909850005',
                'nama' => 'Tono Sudarto',
                'id_rt' => 2,
                'id_keluarga' => null,
                'rw' => '001',
                'jenis_kelamin' => 'Laki-laki',
                'golongan_darah' => 'O',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '1985-09-09',
                'alamat_ktp' => 'Jl. Magelang No. 14',
                'alamat_domisili' => 'Jl. Magelang No. 14',
                'no_hp' => '08456789014',
                'agama' => 'Buddha',
                'pekerjaan' => 'Pengusaha',
                'status_kawin' => 'Kawin',
                'gambar_ktp' => 'tono_ktp.jpg',
                'status_warga' => 'Aktif',
                'catatan_status' => 'Warga telah terdaftar dalam sistem',
                'status_keluarga' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Warga RT 3
            [
                'nik' => '3507231111850001',
                'nama' => 'Bambang Sutomo',
                'id_rt' => 3,
                'id_keluarga' => null,
                'rw' => '001',
                'jenis_kelamin' => 'Laki-laki',
                'golongan_darah' => 'O',
                'tempat_lahir' => 'Surabaya',
                'tanggal_lahir' => '1985-11-11',
                'alamat_ktp' => 'Jl. Gubeng No. 11',
                'alamat_domisili' => 'Jl. Gubeng No. 11',
                'no_hp' => '082345678901',
                'agama' => 'Buddha',
                'pekerjaan' => 'Dokter',
                'status_kawin' => 'Kawin',
                'gambar_ktp' => 'bambang_ktp.jpg',
                'status_warga' => 'Aktif',
                'catatan_status' => 'Warga telah terdaftar dalam sistem',
                'status_keluarga' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => '3507230101900002',
                'nama' => 'Sri Wulandari',
                'id_rt' => 3,
                'id_keluarga' => null,
                'rw' => '001',
                'jenis_kelamin' => 'Perempuan',
                'golongan_darah' => 'A',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '1990-01-01',
                'alamat_ktp' => 'Jl. Gubeng No. 12',
                'alamat_domisili' => 'Jl. Gubeng No. 12',
                'no_hp' => '082345678902',
                'agama' => 'Islam',
                'pekerjaan' => 'Guru',
                'status_kawin' => 'Belum Kawin',
                'gambar_ktp' => 'sri_ktp.jpg',
                'status_warga' => 'Aktif',
                'catatan_status' => 'Warga telah terdaftar dalam sistem',
                'status_keluarga' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => '3507230202920003',
                'nama' => 'Haryo Leksono',
                'id_rt' => 3,
                'id_keluarga' => null,
                'rw' => '001',
                'jenis_kelamin' => 'Laki-laki',
                'golongan_darah' => 'B',
                'tempat_lahir' => 'Surabaya',
                'tanggal_lahir' => '1992-02-02',
                'alamat_ktp' => 'Jl. Gubeng No. 13',
                'alamat_domisili' => 'Jl. Gubeng No. 13',
                'no_hp' => '082345678903',
                'agama' => 'Kristen',
                'pekerjaan' => 'Dokter',
                'status_kawin' => 'Kawin',
                'gambar_ktp' => 'rudi_ktp.jpg',
                'status_warga' => 'Aktif',
                'catatan_status' => 'Warga telah terdaftar dalam sistem',
                'status_keluarga' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => '3507230303850004',
                'nama' => 'Tuti Sugiarti',
                'id_rt' => 3,
                'id_keluarga' => null,
                'rw' => '001',
                'jenis_kelamin' => 'Perempuan',
                'golongan_darah' => 'AB',
                'tempat_lahir' => 'Bandung',
                'tanggal_lahir' => '1995-03-03',
                'alamat_ktp' => 'Jl. Gubeng No. 14',
                'alamat_domisili' => 'Jl. Gubeng No. 14',
                'no_hp' => '082345678904',
                'agama' => 'Hindu',
                'pekerjaan' => 'Pengusaha',
                'status_kawin' => 'Belum Kawin',
                'gambar_ktp' => 'tuti_ktp.jpg',
                'status_warga' => 'Aktif',
                'catatan_status' => 'Warga telah terdaftar dalam sistem',
                'status_keluarga' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => '3507230404980005',
                'nama' => 'Leli Ayu Susanto',
                'id_rt' => 3,
                'id_keluarga' => null,
                'rw' => '001',
                'jenis_kelamin' => 'Perempuan',
                'golongan_darah' => 'O',
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '1998-04-04',
                'alamat_ktp' => 'Jl. Gubeng No. 15',
                'alamat_domisili' => 'Jl. Gubeng No. 15',
                'no_hp' => '082345678905',
                'agama' => 'Buddha',
                'pekerjaan' => 'Pengusaha',
                'status_kawin' => 'Belum Kawin',
                'gambar_ktp' => 'leli_ktp.jpg',
                'status_warga' => 'Aktif',
                'catatan_status' => 'Warga telah terdaftar dalam sistem',
                'status_keluarga' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Warga RT 4
            [
                'nik' => '3507230101900006',                
                'nama' => 'Rudi Hartono Agung Supriyadi',
                'id_rt' => 4,
                'id_keluarga' => null,
                'rw' => '001',
                'jenis_kelamin' => 'Laki-laki',
                'golongan_darah' => 'A',
                'tempat_lahir' => 'Surabaya',
                'tanggal_lahir' => '1990-01-01',
                'alamat_ktp' => 'Jl. Gubeng No. 16',
                'alamat_domisili' => 'Jl. Gubeng No. 16',
                'no_hp' => '082345678906',
                'agama' => 'Islam',
                'pekerjaan' => 'Pengusaha',
                'status_kawin' => 'Kawin',
                'gambar_ktp' => 'rudi4_ktp.jpg',
                'status_warga' => 'Aktif',
                'catatan_status' => 'Warga telah terdaftar dalam sistem',
                'status_keluarga' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [                
                'nik' => '3507230202920007',
                'nama' => 'Siti Aisyah Fatimah',
                'id_rt' => 4,
                'id_keluarga' => null,
                'rw' => '001',
                'jenis_kelamin' => 'Perempuan',
                'golongan_darah' => 'B',
                'tempat_lahir' => 'Malang',
                'tanggal_lahir' => '1992-02-02',
                'alamat_ktp' => 'Jl. Gubeng No. 17',
                'alamat_domisili' => 'Jl. Gubeng No. 17',
                'no_hp' => '082345678907',
                'agama' => 'Kristen',
                'pekerjaan' => 'Pengusaha',
                'status_kawin' => 'Belum Kawin',
                'gambar_ktp' => 'siti4_ktp.jpg',
                'status_warga' => 'Aktif',
                'catatan_status' => 'Warga telah terdaftar dalam sistem',
                'status_keluarga' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [                
                'nik' => '3507230303940008',                
                'nama' => 'Ayu Lestari Wati',
                'id_rt' => 4,
                'id_keluarga' => null,
                'rw' => '001',
                'jenis_kelamin' => 'Perempuan',
                'golongan_darah' => 'AB',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '1994-03-03',
                'alamat_ktp' => 'Jl. Gubeng No. 18',
                'alamat_domisili' => 'Jl. Gubeng No. 18',
                'no_hp' => '082345678908',
                'agama' => 'Hindu',
                'pekerjaan' => 'Pengusaha',
                'status_kawin' => 'Belum Kawin',
                'gambar_ktp' => 'ayu4_ktp.jpg',
                'status_warga' => 'Aktif',
                'catatan_status' => 'Warga telah terdaftar dalam sistem',
                'status_keluarga' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => '3507230404960009',
                'nama' => 'Rahmat Hidayat Wijaya',
                'id_rt' => 4,
                'id_keluarga' => null,
                'rw' => '001',
                'jenis_kelamin' => 'Laki-laki',
                'golongan_darah' => 'O',
                'tempat_lahir' => 'Bandung',
                'tanggal_lahir' => '1996-04-04',
                'alamat_ktp' => 'Jl. Gubeng No. 19',
                'alamat_domisili' => 'Jl. Gubeng No. 19',
                'no_hp' => '082345678909',
                'agama' => 'Buddha',
                'pekerjaan' => 'Pengusaha',
                'status_kawin' => 'Kawin',
                'gambar_ktp' => 'rahmat4_ktp.jpg',
                'status_warga' => 'Aktif',
                'catatan_status' => 'Warga telah terdaftar dalam sistem',
                'status_keluarga' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => '3507230505980010',
                'nama' => 'Lia Sari Wulandari',
                'id_rt' => 4,
                'id_keluarga' => null,
                'rw' => '001',
                'jenis_kelamin' => 'Perempuan',
                'golongan_darah' => 'A',
                'tempat_lahir' => 'Surabaya',
                'tanggal_lahir' => '1998-05-05',
                'alamat_ktp' => 'Jl. Gubeng No. 20',
                'alamat_domisili' => 'Jl. Gubeng No. 20',
                'no_hp' => '082345678910',
                'agama' => 'Islam',
                'pekerjaan' => 'Pengusaha',
                'status_kawin' => 'Belum Kawin',
                'gambar_ktp' => 'lia4_ktp.jpg',
                'status_warga' => 'Aktif',
                'catatan_status' => 'Warga telah terdaftar dalam sistem',
                'status_keluarga' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ]);
    }
}
